### PR TITLE
Posters listing page

### PR DESCRIPTION
**Pull request by ewels**
New page listing all posters.

Deployment preview direct link: https://deploy-preview-256--nextflow-summit-2024.netlify.app/2024/barcelona/agenda/posters/

Todo:

- [x] If a poster PDF is updated, show it embedded on the abstract detail page, plus show icon on poster listing oage
- [x] Sort posters (alphabetical by author name?
- [x] Figure out where to link to this page from

@netlify /2024/barcelona/posters/

### CODE REVIEW

**Review by christopher-hakkaart — APPROVED** [review]
Argh, sorry! I didn't accept this. It looks good to me!

**Comment by ewels** [comment]
No worries! Any thought on where we should link to it from?

**Comment by christopher-hakkaart** [comment]
IMO - It's some of the content people will be most interested in, so the main nav bar.

Option 1: Squeeze it in. If it doesn't fit I would drop "Why attend".
Option 2: Make the "Poster session" clickable in the agenda and link it out from there

**Comment by christopher-hakkaart** [comment]
We had a chat in the weekly, plan is to keep "Why attend?" but drop it from the nav bar. The page should still exist because it's been linked in previous emails, so we can add a link on the home page to keep it alive but not make it a focus.

**Comment by ewels** [comment]
Realised that the posters are already sorted alphabetically by title, so that's probably fine.

Everything else is done now I think, good for review + merge.

I uploaded a fake poster for @franbonath for testing, this can be removed from Sessionize prior to merge + deploy.

**Comment by christopher-hakkaart** [comment]
It looks good to me. I was expecting more posters though, are they all rendering? Maybe something in Sessionize.

**Comment by ewels** [comment]
To do before merge:

- [ ] Remove time from poster cards
- [ ] Add details of poster session to top of index page
- [ ] Check that all poster sessions are shown

**Comment by ewels** [comment]
Ok figured it out - I was filtering sessions on whether they had applied to give a poster. Not whether they were selected as a poster. Fixed now.

**Pull request merged**
